name: Gradle-CI
on: push
jobs:
  clone:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: upload-repo
        uses: actions/upload-artifact@v2
        with:
          name: code
          path: .
  build:
    needs: [clone]
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: code
          path: .
      - name: build
        run: |
          chmod +x ./ci/build-app.sh
          ./ci/build-app.sh

  test:
    needs: [clone]
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: code
          path: .
      - name: test
        run: |
          chmod +x ./ci/unit-test-app.sh
          ./ci/unit-test-app.sh

  build-docker:
    needs: [clone,build,test]
    runs-on: dind-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: code
          path: .
      - name: build
        env:
          docker_username: ${{ secrets.DOCKER_USERNAME }}
        run: |
          chmod +x ./ci/build-docker.sh
          GIT_COMMIT="GA-$GITHUB_SHA" ./ci/build-docker.sh
      - name: push
        env:
          docker_username: ${{ secrets.DOCKER_USERNAME }}
          docker_password: ${{ secrets.DOCKER_PASSWORD }
        run: |
          chmod +x ./ci/push-docker.sh
          GIT_COMMIT="GA-$GITHUB_SHA" ./ci/push-docker.sh